name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  reuse:
    uses: ./.github/workflows/reusable-action.yml@main
    with:
      who-to-greet: "Tom"
    secrets: inherit

  label:
    uses: ./.github/workflows/reusable-another-action.yml@main
