name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  hoge:
    uses: ./.github/workflows/reusable-action.yml
    with:
      who-to-greet: "Tom"
    secrets: inherit
